#Minecraft server properties
#Sat May 09 20:28:23 CST 2026
allow-flight=true
allow-nether=true
announce-player-achievements=true
difficulty=3
enable-command-block=true
enable-query=false
enable-rcon=false
force-gamemode=false
gamemode=0
generate-structures=true
generator-settings=
hardcore=false
level-name=World
level-seed=
level-type=rwg
max-build-height=256
max-players=20
max-tick-time=0
motd=GT\:New Horizons 2.8.4
online-mode=true
op-permission-level=2
pause-when-empty-seconds=0
player-idle-timeout=0
pvp=true
resource-pack=
server-id=unnamed
server-ip=
server-name=
server-port=25565
snooper-enabled=true
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=1
texture-pack=
view-distance=10
white-list=false